In [49]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import Imputer
from sklearn.feature_selection import SelectPercentile
from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import KFold
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import RFE
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import LinearSVC
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import Imputer
from sklearn.neural_network import MLPRegressor
from sklearn.neural_network import MLPClassifier
from sklearn.feature_selection import SelectKBest
from sklearn.neighbors import RadiusNeighborsRegressor
from sklearn.linear_model import BayesianRidge
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import Imputer
from sklearn.feature_selection import SelectPercentile
from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import KFold
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import Imputer
from sklearn.feature_selection import SelectPercentile
from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import KFold
from sklearn.neural_network import MLPRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from ModelFunctions import DecisionTreeFunc, KnnFunc, BayesianRidgeFunc, NeuralNetworkFunc, LinearRegFunc
from sklearn.linear_model import LinearRegression

# Set Up Bayesian Ridge Model with Train Data

In [50]:
train = pd.read_csv('data/mixed_prepared_features.csv', index_col=0)
train = train.drop(features.columns[0], axis=1)
train_features = train.drop(columns=['score_dif', 'TeamID']).rename(index=str, columns={"WTeamID": "TeamID1", "LTeamID": "TeamID2"}).values
train_outcome = train.score_dif.values

BPred = BayesianRidgeFunc(train_features, train_outcome)

# Data Prep for Round 1

In [51]:
Round1 = pd.read_csv('data/round_one_match.csv')
teamAvgStats = pd.read_csv('data/team_summary_stats.csv', index_col=0)
teamAvgStats = teamAvgStats[teamAvgStats['Season'] == 2019]
teamAvgStats = teamAvgStats.drop(columns=['Season'])
test1 = pd.merge(Round1, teamAvgStats, how='left', left_on=['TeamID1'], right_on=['TeamID'])
test1 = pd.merge(test1, teamAvgStats, how='left', left_on=['TeamID2'], right_on=['TeamID'], suffixes=('', '_t2'))
test1 = test1.drop(columns=['TeamID', 'TeamID_t2'])
test1.loc[:, 'FGM':'PF'] = test1.loc[:, 'FGM':'PF'].values - test1.loc[:, 'FGM_t2':'PF_t2'].values
test1 = test1.loc[:, 'TeamID1':'PF']
test1

,TeamID1,TeamID2,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF
0,1433,1416,0.230108,3.248387,0.327957,4.187097,-2.004301,-4.707527,0.843011,-1.035484,0.468817,2.265591,2.298925,-0.013978,3.104301
1,1280,1251,1.096774,3.838710,0.129032,-0.258065,2.774194,5.032258,3.967742,0.000000,0.129032,2.193548,2.000000,2.645161,1.419355
2,1439,1387,1.967742,-3.193548,4.064516,5.806452,-1.064516,-6.483871,-4.870968,-2.193548,2.580645,-1.870968,-0.774194,-1.741935,-2.741935
3,1257,1278,0.321573,0.885081,3.143145,8.227823,-0.260081,-3.409274,-1.431452,2.226815,-1.395161,0.147177,-0.371976,-1.161290,0.671371
4,1279,1328,0.610887,-0.798387,1.568548,3.333669,2.053427,0.429435,0.748992,-3.891129,1.764113,0.586694,1.449597,0.454637,2.379032
5,1458,1332,0.625000,0.531250,-0.397177,-3.047379,-1.677419,-0.717742,-1.560484,2.571573,-0.820565,-2.454637,-2.683468,0.161290,-2.526210
6,1243,1414,-3.032258,-4.548387,0.161290,1.548387,-0.258065,0.322581,-2.451613,-4.645161,0.419355,-0.258065,2.129032,-2.161290,-2.677419
7,1437,1388,-1.674487,0.003910,3.253177,10.428152,1.831867,2.944282,0.601173,-0.167155,4.132942,0.553275,-0.612903,0.454545,-0.518084
8,1153,1234,-1.419355,0.096774,-1.580645,-3.419355,-2.903226,-2.967742,2.258065,-2.322581,-1.967742,-1.612903,0.064516,1.225806,-0.193548
9,1393,1124,-1.703629,-1.528226,0.003024,0.864919,1.221774,1.494960,-2.511089,-0.522177,-1.746976,-0.945565,2.055444,0.101815,-1.621976
10,1266,1293,-3.097887,-3.095662,1.729700,1.590656,0.299221,-0.195773,-1.576196,1.660734,-3.598443,1.691880,-2.273637,0.005562,2.046719
11,1199,1436,1.225806,3.709677,-0.451613,0.225806,1.193548,2.129032,2.645161,0.225806,1.451613,2.451613,1.806452,0.419355,2.806452
12,1305,1196,3.645161,2.387097,0.709677,0.677419,5.290323,7.677419,-1.354839,5.483871,3.000000,-1.387097,-0.967742,0.064516,-0.516129
13,1429,1449,2.991398,4.270968,0.479570,0.908602,2.017204,1.476344,0.918280,6.849462,5.551613,-1.084946,-2.704301,-1.569892,0.380645
14,1120,1308,0.298851,1.863218,2.166667,2.537931,-0.395402,-1.587356,-0.793103,-2.252874,0.319540,0.529885,3.275862,2.386207,0.526437
15,1242,1318,1.043988,4.404692,-2.273705,-4.086999,-0.292278,1.071359,3.127077,2.825024,-0.913978,2.144673,0.654936,1.590420,1.096774
16,1235,1326,4.161290,3.935484,1.064516,1.483871,-1.000000,-1.419355,0.000000,0.064516,1.709677,-1.322581,1.354839,2.000000,-2.967742
17,1459,1371,3.100000,1.066667,3.900000,4.700000,-2.700000,-3.566667,-0.033333,-0.666667,1.033333,-1.600000,-0.900000,-1.066667,-0.766667

# Predictions for Round 1

In [52]:
BPred.predict(test1)

array([ -0.95380355,   5.64293304,   7.28381962,   2.2015922 ,
         7.90949049,  -1.65046813,  -3.43857918,   2.06015378,
         4.61481625,   1.08359477, -11.37756739,   0.04912853,
         7.14694192,   4.57861464,   2.66871743,  -0.72267158,
        12.5635421 ,   8.57346995])

# Round 2 Data Prep

In [53]:
Round2 = pd.read_csv('data/round_two_match.csv')
teamAvgStats = pd.read_csv('data/team_summary_stats.csv', index_col=0)
teamAvgStats = teamAvgStats[teamAvgStats['Season'] == 2019]
teamAvgStats = teamAvgStats.drop(columns=['Season'])
test2 = pd.merge(Round2, teamAvgStats, how='left', left_on=['TeamID1'], right_on=['TeamID'])
test2 = pd.merge(test2, teamAvgStats, how='left', left_on=['TeamID2'], right_on=['TeamID'], suffixes=('', '_t2'))
test2 = test2.drop(columns=['TeamID', 'TeamID_t2'])
test2.loc[:, 'FGM':'PF'] = test2.loc[:, 'FGM':'PF'].values - test2.loc[:, 'FGM_t2':'PF_t2'].values
test2 = test2.loc[:, 'TeamID1':'PF']
test2

,TeamID1,TeamID2,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF
0,1181,1416,5.778495,11.183871,0.682796,5.348387,-0.810753,-2.707527,3.746237,1.351613,2.630108,1.233333,3.750538,2.534409,-0.992473
1,1280,1439,1.741935,4.387097,-1.258065,-1.870968,0.709677,2.032258,2.612903,0.451613,-1.225806,1.903226,1.516129,2.806452,1.645161
2,1268,1261,-3.000000,-5.967742,0.419355,-0.709677,-4.387097,-5.548387,-2.419355,3.064516,0.096774,0.032258,-4.838710,0.354839,-3.064516
3,1257,1277,-3.130040,-0.050403,0.272177,3.195565,0.965726,0.429435,-0.689516,-2.321573,-5.846774,-0.530242,-0.759073,-2.580645,-0.006048
4,1438,1279,-0.781720,-3.651613,0.339785,-2.077419,-2.643011,-2.575269,-0.901075,1.616129,0.148387,-3.707527,-1.787097,0.418280,-3.695699
5,1332,1414,-1.399194,-2.724798,0.848790,3.369960,0.322581,-0.185484,-2.213710,-3.861895,0.239919,0.164315,2.425403,-0.354839,-1.215726
6,1437,1345,-1.838710,-3.741935,0.838710,3.290323,1.193548,1.709677,-1.774194,0.096774,-0.064516,0.387097,-1.161290,-1.096774,-1.064516
7,1153,1397,-5.190323,-2.845161,-0.220430,-0.272043,0.046237,1.668817,2.280645,-3.846237,-4.754839,-0.523656,0.552688,-0.750538,-1.309677
8,1211,1393,8.369318,4.140152,-0.118371,-2.854167,2.571970,1.101326,-1.298295,4.903409,6.055871,-1.948864,-0.735795,0.641098,-1.220644
9,1293,1199,3.355951,1.837597,0.302558,-0.010011,-1.234705,-1.868743,-0.585095,0.855395,4.179088,-1.175751,0.015573,0.091212,-3.143493
10,1138,1403,4.138710,10.380645,2.476344,8.925806,1.015054,2.387097,3.730108,2.517204,2.772043,-0.323656,0.140860,-0.904301,0.691398
11,1305,1444,3.677419,2.064516,2.096774,2.903226,2.870968,3.516129,-1.516129,1.709677,3.741935,-5.225806,1.903226,1.451613,-0.806452
12,1314,1429,3.363441,8.341935,1.101075,1.865591,-0.113978,0.039785,2.630108,1.086022,2.190323,0.988172,1.155914,-0.688172,-1.574194
13,1120,1318,1.151515,6.693939,1.409091,4.248485,-0.503030,0.427273,5.030303,-2.454545,0.400000,1.390909,2.848485,2.648485,2.733333
14,1235,1222,1.419355,-0.322581,-0.903226,-2.354839,-0.645161,-1.322581,-2.774194,-2.967742,0.354839,-0.548387,0.483871,0.129032,-3.935484
15,1459,1246,2.848387,4.616129,4.834409,9.326882,-6.137634,-7.431183,-1.312903,-2.469892,0.990323,-1.508602,0.133333,-2.034409,1.403226

# Predictions for Round 2

In [54]:
BPred.predict(test2)

array([14.74388979,  1.90022642, -6.01189959, -9.77497945, 10.12389755,
        0.92921308, -2.25768996, -3.25895477, 17.67946385,  9.8473095 ,
        5.30157499, 20.54748008,  0.57313281,  6.34134404, -0.08602435,
       -0.76477955])

# Round 3 Data Prep

In [55]:
Round3 = pd.read_csv('data/round_three_match.csv')
teamAvgStats = pd.read_csv('data/team_summary_stats.csv', index_col=0)
teamAvgStats = teamAvgStats[teamAvgStats['Season'] == 2019]
teamAvgStats = teamAvgStats.drop(columns=['Season'])
test3 = pd.merge(Round3, teamAvgStats, how='left', left_on=['TeamID1'], right_on=['TeamID'])
test3 = pd.merge(test3, teamAvgStats, how='left', left_on=['TeamID2'], right_on=['TeamID'], suffixes=('', '_t2'))
test3 = test3.drop(columns=['TeamID', 'TeamID_t2'])
test3.loc[:, 'FGM':'PF'] = test3.loc[:, 'FGM':'PF'].values - test3.loc[:, 'FGM_t2':'PF_t2'].values
test3 = test3.loc[:, 'TeamID1':'PF']
test3

,TeamID1,TeamID2,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF
0,1181,1280,3.161290,6.096774,-1.000000,1.903226,1.516129,3.032258,2.000000,4.322581,1.838710,-0.354839,1.322581,1.870968,-1.258065
1,1261,1277,0.290323,4.064516,-1.419355,-0.483871,2.774194,3.387097,2.451613,-5.096774,-5.967742,0.258065,3.903226,-1.193548,1.322581
2,1438,1332,0.391667,-2.668750,0.845833,-1.931250,0.066667,-0.583333,-0.558333,1.381250,1.037500,-2.839583,-2.212500,-0.033333,-3.254167
3,1345,1397,-3.190323,-0.393548,3.005376,7.340860,-2.534409,-2.395699,1.893548,-2.588172,-4.141935,-0.491398,0.681720,-1.169892,-0.083871
4,1211,1293,2.664577,0.032393,0.098224,-1.011494,1.834901,1.723093,-1.385580,2.332288,0.936259,-1.912226,0.304075,1.071055,-0.215256
5,1138,1305,2.654839,6.703226,0.831183,3.409677,-2.888172,-3.419355,3.375269,-0.192473,1.675269,1.740860,1.011828,0.063441,1.336559
6,1314,1120,3.763441,5.775269,-2.198925,-5.367742,1.952688,1.773118,1.096774,8.086022,4.556989,0.721505,-1.677419,-1.154839,-1.507527
7,1222,1246,0.322581,3.935484,3.322581,8.870968,-4.354839,-5.064516,0.645161,1.645161,1.483871,-1.161290,0.580645,-0.580645,2.741935

# Predictions for Round 3

In [56]:
BPred.predict(test3)

array([11.07934458,  1.49814455,  9.65000216,  0.23110251, 11.20263721,
        2.04784705,  1.71878797,  2.88030639])

# Round 4 Data Prep

In [57]:
Round4 = pd.read_csv('data/round_four_match.csv')
teamAvgStats = pd.read_csv('data/team_summary_stats.csv', index_col=0)
teamAvgStats = teamAvgStats[teamAvgStats['Season'] == 2019]
teamAvgStats = teamAvgStats.drop(columns=['Season'])
test4 = pd.merge(Round4, teamAvgStats, how='left', left_on=['TeamID1'], right_on=['TeamID'])
test4 = pd.merge(test4, teamAvgStats, how='left', left_on=['TeamID2'], right_on=['TeamID'], suffixes=('', '_t2'))
test4 = test4.drop(columns=['TeamID', 'TeamID_t2'])
test4.loc[:, 'FGM':'PF'] = test4.loc[:, 'FGM':'PF'].values - test4.loc[:, 'FGM_t2':'PF_t2'].values
test4 = test4.loc[:, 'TeamID1':'PF']
test4

,TeamID1,TeamID2,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF
0,1181,1261,2.193548,2.806452,0.645161,3.290323,-2.548387,-1.419355,0.096774,3.258065,2.967742,-0.225806,0.290323,2.580645,-2.741935
1,1438,1345,-0.943011,-6.006452,-1.305376,-6.174194,-0.965591,-1.704301,-3.126882,1.454839,0.341935,-1.675269,-0.948387,-0.130108,-3.082796
2,1211,1138,1.881818,-5.284848,-1.978788,-7.366667,2.230303,0.757576,-3.087879,1.057576,1.278788,-1.603030,0.178788,1.518182,-2.372727
3,1314,1222,4.322581,7.322581,-0.387097,-1.645161,1.903226,1.806452,0.838710,1.870968,4.096774,1.774194,0.741935,-0.741935,-1.612903

# Predictions for Round 4

In [58]:
BPred.predict(test4)

array([ 8.37412124,  3.75217094, 13.83631547, -1.24562045])

# Round 5 Data Prep

In [59]:
Round5 = pd.read_csv('data/round_five_match.csv')
teamAvgStats = pd.read_csv('data/team_summary_stats.csv', index_col=0)
teamAvgStats = teamAvgStats[teamAvgStats['Season'] == 2019]
teamAvgStats = teamAvgStats.drop(columns=['Season'])
test5 = pd.merge(Round5, teamAvgStats, how='left', left_on=['TeamID1'], right_on=['TeamID'])
test5 = pd.merge(test5, teamAvgStats, how='left', left_on=['TeamID2'], right_on=['TeamID'], suffixes=('', '_t2'))
test5 = test5.drop(columns=['TeamID', 'TeamID_t2'])
test5.loc[:, 'FGM':'PF'] = test5.loc[:, 'FGM':'PF'].values - test5.loc[:, 'FGM_t2':'PF_t2'].values
test5 = test5.loc[:, 'TeamID1':'PF']
test5

,TeamID1,TeamID2,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF
0,1181,1211,-1.536657,3.968719,-0.271750,3.215054,-1.374389,0.468231,4.067449,-0.639296,-2.115347,2.636364,1.938416,1.482893,-0.286413
1,1438,1222,-1.007527,-5.619355,-0.821505,-5.077419,-1.449462,-2.833333,-3.191398,-2.448387,-0.593548,-2.513978,-0.980645,-0.420430,-4.405376

# Predictions for Round 5

In [60]:
BPred.predict(test5)

array([-1.02497527,  3.80328321])

# Final Round Data Prep

In [61]:
Round6 = pd.read_csv('data/round_six_match.csv')
teamAvgStats = pd.read_csv('data/team_summary_stats.csv', index_col=0)
teamAvgStats = teamAvgStats[teamAvgStats['Season'] == 2019]
teamAvgStats = teamAvgStats.drop(columns=['Season'])
test6 = pd.merge(Round6, teamAvgStats, how='left', left_on=['TeamID1'], right_on=['TeamID'])
test6 = pd.merge(test6, teamAvgStats, how='left', left_on=['TeamID2'], right_on=['TeamID'], suffixes=('', '_t2'))
test6 = test6.drop(columns=['TeamID', 'TeamID_t2'])
test6.loc[:, 'FGM':'PF'] = test6.loc[:, 'FGM':'PF'].values - test6.loc[:, 'FGM_t2':'PF_t2'].values
test6 = test6.loc[:, 'TeamID1':'PF']
test6

,TeamID1,TeamID2,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF
0,1211,1438,6.415152,6.715152,-0.745455,0.733333,4.630303,5.590909,0.478788,2.990909,3.612121,1.29697,1.945455,1.518182,1.627273

# Predictions for Final Round

In [62]:
BPred.predict(test6)

array([8.95069993])